
export const CONTROL_CMDS ={
  PAGE_SWITCH:"PAGE_SWITCH",
  GREEN_ADD:"GREEN_ADD",//绿色发展地图控制
  GREEN_CLOSE:"GREEN_CLOSE",//绿色发展弹窗关闭
  VIDEO_ID:"VIDEO_ID",//视频控制
  CHANGE_VIDEO_BASE:'CHANGE_VIDEO_BASE',
  FARM_ID:"FARM_ID",//farm农机作业轨迹打开
  FARM_CLOSE:"FARM_CLOSE",//关闭农机作业轨迹
  FARM_ADD:"FARM_ADD",//农机地图控制

  HOME_CHANGE_AREA:"HOME_CHANGE_AREA",
  //三区图层过滤
  THREE_AREA_FILTER:"THREE_AREA_FILTER",
  HOME_ADD:"HOME_ADD",
  VIDEO_CONTROL:"VIDEO_CONTROL",//基地管控
  VIDEO_CHANGE:"VIDEO_CHANGE",
  WISDOM_CONTROL:"WISDOM_CONTROL",//智慧物联
  CLOSE_THREE_AREA_SHAPE:"CLOSE_THREE_AREA_SHAPE",

  GREEN_GIS:'GREEN_GIS',
  ORDER_DETAIL:'ORDER_DETAIL',
  ORDER_BACK:'ORDER_BACK',
  CHOOSE_AREA_GIS:'CHOOSE_AREA_GIS',
  CHANGE_GIS_MODEL:'CHANGE_GIS_MODEL',
  SHOW_AREA_MODEL:'SHOW_AREA_MODEL'
};
